### ISSUE TITLE
DOCS: RDS PGSQL

### ISSUE THREAD

**Issue by tip-dteller** [danny-avila/rag_api#17]
Hi,
Can you please add to documentation that when running PGSQL on RDS AWS (may apply to other managed services).
You have to login as Admin user for that RDS cluster and add the extension to the database.

1. login to RDS with admin user
2. run on the the required database - .
```CREATE EXTENSION vector;```

reason why this had to be done - unless youre using master credentials or a dedicated superuser, its gonna be added manually.

**Comment by danny-avila** [comment]
Feel free to make a PR, but I will say you should include a full setup for AWS in the documentation, because this is not the default setup.

**Comment by tip-dteller** [comment]
Will do, i will check a few more things to make it as accurate and friendly as possible.
thanks!

**Comment by danny-avila** [comment]
thank you 🙏

**Comment by tip-dteller** [comment]
#20 added PR
