### ISSUE TITLE
Create version tags for the rag-api docker image

### ISSUE THREAD

**Issue by rcdailey** [danny-avila/rag_api#33]
Looking at the officially published docker image here: https://github.com/danny-avila/rag_api/pkgs/container/librechat-rag-api-dev-lite

I'd like to see docker tags published that correspond to the Github Releases seen here: https://github.com/danny-avila/rag_api/releases

The reason is because I use Renovate to upgrade docker images in my homelab, and without release-based tags it is very difficult to keep up with changelogs. I also think it would be healthy to do regular releases for folks that prefer more stable releases (Not suggesting that the current releases are *not* stable, but less updates over time is usually preferred to keep services stable in my environment).

Is this something the maintainers would be open to?

**Comment by danny-avila** [comment]
@rcdailey Open to this!

**Comment by rcdailey** [comment]
@danny-avila thank you so much for the change! Is it still too soon to expect a tag for the current release? I've been checking here:

https://github.com/danny-avila/rag_api/pkgs/container/librechat-rag-api-dev-lite
