### ISSUE TITLE
README section for MongoDB should be updated

### ISSUE THREAD

**Issue by jegraham-amplify** [danny-avila/rag_api#52]
The [README section about using MongoDB](https://github.com/danny-avila/rag_api?tab=readme-ov-file#use-atlas-mongodb-as-vector-database) should be updated to include some information:

1. List any known issues, or functionality that does not work. If you know that things are not fully supported, please call that out here. Currently, the only indication that things might not work 100% is a one-line message that's logged when the service is started.
2. The section about setting up the vector search index does not make it clear that the index needs to have the same name as your vector collection for the code to work (true after [this fix](https://github.com/danny-avila/rag_api/pull/50). Previously, the index needed the name `default`). It should be explicitly stated that the vector search index name needs to match the configured `COLLECTION_NAME`.

**Comment by ScarFX** [comment]
Environmental variables refactored in order to allow different names for vector search index and vector collection as seen in [new readme](https://github.com/danny-avila/rag_api/pull/74/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
