### ISSUE TITLE
Setup RAG on HuggingFace deployment

### ISSUE THREAD

**Issue by sylvainlapeyrade** [danny-avila/rag_api#57]
Hello,

Thanks a lot for your amazing work! I have deployed an instance of LibreChat to HuggingFace with MongoDB Atlas and I would like to use RAG. I've set the RAG_OPENAI_API_KEY to my OpenAI key, but I'm missing a RAG_API_URL.

I would like to know the simplest way to configure one from there.

Thank you very much!

**Comment by nickturrietta** [comment]
@sylvainlapeyrade Did you ever figure this out? My setup is the same as yours and I'm having trouble as well.

**Comment by sylvainlapeyrade** [comment]
No actually no I didn’t really take the time to dig this. I know it’s working on the official demo version, so it’s definitely doable. Please let me know if you find the solution 🙏

**Comment by nickturrietta** [comment]
> No actually no I didn’t really take the time to dig this. I know it’s working on the official demo version, so it’s definitely doable. Please let me know if you find the solution 🙏

Copy that. Will do.

**Comment by sylvainlapeyrade** [comment]
Hey, thank you very much for the heads up! I guess I can close the issue then.
