### ISSUE TITLE
I have error when attache file csv.How to solve?

### ISSUE THREAD

**Issue by angpao** [danny-avila/rag_api#83]
{"level":"error","message":"Error embedding file File embedding failed.","stack":"Error: File embedding failed.\n    at uploadVectors (/app/api/server/services/Files/VectorDB/crud.js:84:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async processFileUpload (/app/api/server/services/Files/process.js:348:7)\n    at async /app/api/server/routes/files/files.js:157:5"}
{"level":"error","message":"[/files] Error processing file: File embedding failed.","stack":"Error: File embedding failed.\n    at uploadVectors (/app/api/server/services/Files/VectorDB/crud.js:95:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async processFileUpload (/app/api/server/services/Files/process.js:348:7)\n    at async /app/api/server/routes/files/files.js:157:5"}

**Comment by danny-avila** [comment]
Not enough information here, try reproducing it here to confirm it's really an issue

https://librechat-librechat.hf.space/
